name: Linux

on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libncurses5-dev libncursesw5-dev
    - name: Compile
      run: make
